public class Main {

    /*  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:

              1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

      By considering the terms in the Fibonacci sequence whose values do not
      exceed four million, find the sum of the even-valued terms.
     */
    public static void main(String[] args) {

        System.out.println(calculateFibElements(4_000_000));

    }

    public static long calculateFibElements(int last) {
        long a = 0, b = 1, c = 0, sum = 0;

        for (int i = 1; i < last; i++) {
            c = a + b;
            a = b;
            b = c;
            System.out.println("element numer " + i + " ciagu fibunacciego to " + c);
            if (c >= 4_000_000) {
                break;
            }
            if (c % 2 == 0) {
                sum += c;
            }
        }
        return sum;
    }

}
